baseURL = "/"
languageCode = "da"
title = "tsundoku.dk"
enableRobotsTXT = true

[params]
  description = "Et minimalistisk bibliotek over bøger jeg har købt og hvorfor."
  assetVersion = "2"

[outputs]
  home = ["HTML", "RSS"]

[minify]
  minifyOutput = true

[pagination]
  pagerSize = 24
